name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release_please
        with:
          release-type: terraform-module
          package-name: terraform-aws-ecr
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-types: '[{"type":"feat","section":"Added","hidden":false},{"type":"fix","section":"Fixed","hidden":false},{"type":"chore","section":"Changed","hidden":false},{"type":"refactor","section":"Changed","hidden":false},{"type":"style","section":"Changed","hidden":false},{"type":"security","section":"Security","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"perf","section":"Performance","hidden":false}]'
          command: manifest
          changelog-sections: '{"header":"## ${version} (${date})","sections":{"Added":"### Added","Changed":"### Changed","Fixed":"### Fixed","Documentation":"### Documentation","Security":"### Security","Performance":"### Performance"}}'
          date-formats: '{"changelogDate":"(%B %d, %Y)"}'
