name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release_please
        with:
          release-type: terraform-module
          package-name: terraform-aws-ecr
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          command: manifest
          changelog-sections: '{"header":"## ${version} (${date})"}'
          date-formats: '{"changelogDate":"%B %d, %Y"}'
